###siteGetAHUQuery
        query getAHUStatusInGroupGRP00 {
            site {
                groups : children(selector:{type: Group,oid:17}) {
                    oid type displayName
                    ahus: children(selector:{type: AHU}) {
                        oid type displayName name
                        controls: search(selector: {target: CONTROL}, pruneDepth: false){
                            oid type displayName name
                              status:targetStatus(target: CONTROL) {origin}
                        }
                    }
                }
            }
        }
