query rackSensorPointsByGroup {
            site {
              groups: children(selector: {type: Group,name: "GRP00"}) @skip(if:false) {
                oid name
                children(selector:{type: Rack}){
                  displayName
                  CTOP: children(selector:{type: CTop}) @skip(if:false){
                  ...rack_sensor_temp
                  }
                  CBOT: children(selector:{type: CBot}) @skip(if:false){
   								...rack_sensor_temp
                  }

                }

                }
              }
            }
  fragment rack_sensor_temp on Model {
                        type
                    displayName
                        oid
                    pointCurrent{
                      value
                    }
  }
