#apiresources.changeCxConfigsDashm_NumGuardUnits_NumMinutesGuardTimer_PercentDeadSensorThreshold_AndSystem_NumMinutesPast    1    3    20    5
num_guard_units=1
num_minutes_guard_timer=3
percent_deadsensor_threshold=100
num_minutes_past=5
allow_num_exceedences_control_initial=10
allow_num_exceedences_guard_initial=10
alm_hot_abs_temp_initial=200
guard_hot_abs_temp_intial=90
allow_num_exceedences_control_default=0
allow_num_exceedences_guard_default=1
alm_hot_abs_temp_default=90
guard_hot_abs_temp_default=90
percent_deadsensor_threshold_default=30
sensor_point_cooling_temp=65.00
sensor_point_hot_temp=100
test_exit_sensor_temp=63.22
test_entry_sensor_temp=61.11


