#Dead Sensor guard test specific
ds_num_guard_units_value=1
ds_num_minutes_guard_timer_value=2
ds_percent_dead_sensor_threshold_default_value=30
ds_num_minutes_past_value=2
dead_sensor_test_temp=66
alarm_dead_sensor_hysteresis_cleanup_value=0
alarm_dead_sensor_threshold_cleanup_value=0
control_dead_sensor_threshold_cleanup_value=0
dead_sensor_alarm_count=1
guard_on="GUARD_ON"  #Guard mode value is 2
guard_off="GUARD_OFF"
group_dead_sensor_alarm_on="ALARM_ON"
group_dead_sensor_alarm_off="ALARM_OFF"
control_dead_sensor_threshold_property_name="ControlDeadSensorThreshold"
grp_dead_sensor_hysteresis_value_default_value=10

