query getCtrlStateValue{
  site {
  groups: children(selector:{type: Group, name: "GRP00"}) {
  children(selector:{type: GroupStatus, name: "Group Status"}){children(selector:{type: State, name: "CtrlState"}){
  name pointCurrent{ value }}}}}}