#Site Editor Web Elements
banner="css:#banner"
tools_button="css:#button-1267-btnEl"
configs_option_in_tools="css:#menuitem-1235-itemEl"
load_template_in_config_popup="css:#button-1299-btnIconEl"
overwrite_checkbox="css:#checkbox-1360-inputEl"
template_dropbox_picker="css:#combo-1358-trigger-picker"
template_option="xpath=//li[contains(text(),'DASHAM_MIX')]"
temperature_scale_option="xpath=//li[contains(text(),'Fahrenheit')]"
temperature_scale_dropbox_picker="css:#combo-1359-trigger-picker"
temperature_scale_dropbox="css:#combo-1359-picker-listEl"
apply_button_load_template="css:#button-1356-btnInnerEl"
save_button="css:#button-1302-btnIconEl"
close_button="css:#button-1303-btnIconEl"