#Site Editor Web Elements
banner="css:#banner"
tools_button="xpath=//div[1]/div/div[1]/div[2]/div/a[1]/span/span/span[2]"
configs_option_in_tools="xpath=//div[12]/div/div/div[2]/div/div[4]/a/span"
load_template_in_config_popup="xpath=//span[contains(text(),'Load Template')]"
overwrite_checkbox="xpath=//div[13]/div[2]/div/div/div/div[1]/div/div/div[3]/div[1]/div/span/input"
template_dropbox_picker="xpath=//div[13]/div[2]/div/div/div/div[1]/div/div/div[1]/div[1]/div/div[2]"
template_option="xpath=//li[contains(text(),'DASHAM_MIX')]"
template_option_RSP="xpath=//li[contains(text(),'DASHAM_RSP_RESET')]"
temperature_scale_option="xpath=//li[contains(text(),'Fahrenheit')]"
temperature_scale_dropbox_picker="xpath=//div[13]/div[2]/div/div/div/div[1]/div/div/div[2]/div[1]/div/div[2]"
temperature_scale_dropbox="xpath=//div[13]/div[2]/div/div/div/div[1]/div/div/div[2]/div[1]/div/div[1]/input"
apply_button_load_template="xpath=//span[contains(text(),'Apply')]"
save_button="xpath=//span[contains(text(),'Save')]"
close_button="xpath=//span[contains(text(),'Close')]"
all_properties_button="xpath=//span[contains(text(),'All Properties')]"
group_dropdown_list="xpath=//div[1]/div/div[1]/div[2]/div/div[2]/div/div/div[2]"
tools_configs_system= "xpath=//div[contains(text(),'SYSTEM')]"
tools_configs_dashm= "xpath=//div[contains(text(),'DASHM') and @unselectable='on']"
yes_button = "xpath=//span[contains(text(),'Yes')]"
sfc_min= "xpath=//div[contains(text(),'SFCMin')]/following::td[1]"
turn_off_limit_24_hr= "xpath=//div[contains(text(),'TurnOffLimit24H')]/following::td[1]"
