# VX AIEngine - Site Editor Web Elements
# Notifications tab
notifications_tab="xpath=//span[contains(text(),'Notifications')]"
suppress_alarm_button="xpath=//span[contains(text(),'Suppress Alarm')]"
suppressed_alarms_button="xpath=//span[contains(text(),'Suppressed Alarms')]"
popup_title = """xpath=//*[@id="messagebox-1001_header-title-textEl"]"""
popup_message = """xpath=//*[@id="messagebox-1001-msg"]"""
ok_button = "xpath=//span[contains(text(),'OK')]"
no_button = "xpath=//span[contains(text(),'Yes')]//following::span[contains(text(),'No')]"
close_button ="xpath=//span[contains(text(),'Close')]"
suppressed_alarms_popup_title = "xpath=//div[contains(text(),'Suppressed Alarms')]"
unsuppress_button="xpath=//span[contains(text(),'Unsuppress')]"
unsuppress_all_button="xpath=//span[contains(text(),'Unsuppress All')]"
clear_overrides_button = "xpath=//span[contains(text(),'Clear Overrides')]"
event_history_button = "xpath=//span[contains(text(),'Event History')]"
show_trends_button = "xpath=//span[contains(text(),'Event History')]//following::span[contains(text(),'Show Trends')]"
bypass_button = "xpath=//div[3]/div/div[2]/div[4]/div/div/div[4]/div/div/div[1]/div/div[3]/div/div/a[1]/span/span/span[2]"
first_alarm_to_suppress = "xpath=//div[3]/div/div[2]/div[4]/div/div/div[8]/div/div/div[2]/div/div[2]/div/div[2]/table[3]/tbody/tr/td[4]/div"